-- 기존 ddl-auto 기반 스키마를 Flyway 베이스라인으로 고정한 파일. dev/prod는 baseline-on-migrate로 스킵되고, 빈 스키마(H2 test 등)에서만 적용됨

    create table admin_account_request (
        approved_at timestamp(6),
        approved_by_member_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        rejected_at timestamp(6),
        updated_at timestamp(6),
        status varchar(20) not null check (status in ('PENDING','APPROVED','REJECTED')),
        name varchar(30) not null,
        email varchar(50) not null,
        reason varchar(500) not null,
        rejected_reason varchar(500),
        password_hash varchar(255) not null,
        primary key (id)
    );

    create table auth_identity (
        email_verified boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        last_login_at timestamp(6),
        member_id bigint not null,
        updated_at timestamp(6),
        provider varchar(20) not null check (provider in ('LOCAL','KAKAO','NAVER','GOOGLE','APPLE')),
        password_hash varchar(255),
        provider_user_id varchar(255) not null,
        primary key (id),
        constraint uk_auth_identity_provider_user_id unique (provider, provider_user_id)
    );

    create table character (
        exp integer not null,
        level integer not null,
        created_at timestamp(6),
        current_health_score bigint not null,
        id bigint generated by default as identity,
        last_status_updated_at timestamp(6) not null,
        member_id bigint not null,
        updated_at timestamp(6),
        current_status varchar(30) not null check (current_status in ('NORMAL','ENERGETIC','TIRED','FULL','SLEEPY','GLOWING','FADED')),
        name varchar(100) not null,
        primary key (id)
    );

    create table character_exp_history (
        exp_amount integer not null,
        character_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        reason varchar(255) not null check (reason in ('MEAL_RECORD','DAILY_COMPLETE','STREAK_BONUS','REPORT_GENERATED','MANUAL_REWARD')),
        primary key (id)
    );

    create table character_status_history (
        health_score integer not null,
        status_date date not null,
        character_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table character_type (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        type_code varchar(50) not null,
        type_name varchar(100) not null,
        base_image varchar(255),
        primary key (id)
    );

    create table email_verification_history (
        is_success boolean not null,
        created_at timestamp(6),
        expire_date_time timestamp(6) not null,
        id bigint generated by default as identity,
        request_at timestamp(6) not null,
        updated_at timestamp(6),
        verified_at timestamp(6),
        code varchar(50) not null,
        email varchar(50) not null,
        primary key (id)
    );

    create table item (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        item_type varchar(50) not null check (item_type in ('HAT','SHIRTS','PANTS')),
        name varchar(50) not null,
        item_image varchar(255),
        primary key (id)
    );

    create table item_possession (
        is_wearing boolean not null,
        character_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        item_id bigint not null,
        updated_at timestamp(6),
        primary key (id)
    );

    create table kkinipop_custom_emoji (
        created_at timestamp(6),
        deleted_at timestamp(6),
        group_id bigint not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        label varchar(20) not null,
        image_key varchar(255) not null,
        primary key (id)
    );

    create table kkinipop_group (
        level integer not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        invite_code varchar(12) not null unique,
        name varchar(40) not null,
        primary key (id)
    );

    create table kkinipop_group_member (
        banned boolean not null,
        created_at timestamp(6),
        group_id bigint not null,
        id bigint generated by default as identity,
        left_at timestamp(6),
        member_id bigint not null,
        updated_at timestamp(6),
        role varchar(10) not null check (role in ('LEADER','MEMBER')),
        primary key (id),
        constraint uk_kkinipop_group_member unique (group_id, member_id)
    );

    create table kkinipop_mission (
        daily_post_limit integer not null,
        border_color varchar(7) not null,
        closed_at timestamp(6),
        created_at timestamp(6),
        end_at timestamp(6) not null,
        group_id bigint not null,
        id bigint generated by default as identity,
        start_at timestamp(6) not null,
        updated_at timestamp(6),
        title varchar(40) not null,
        primary key (id)
    );

    create table kkinipop_post (
        record_date date not null,
        save_to_personal_log boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        group_id bigint not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        mission_id bigint,
        updated_at timestamp(6),
        image_key varchar(255) not null,
        primary key (id)
    );

    create table kkinipop_reaction (
        custom_emoji boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        post_id bigint not null,
        updated_at timestamp(6),
        emoji_code varchar(30) not null,
        emoji_label varchar(30) not null,
        primary key (id)
    );

    create table meal_ai_analysis (
        analyzed_at timestamp(6) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        meal_record_id bigint not null,
        updated_at timestamp(6),
        detected_food_name varchar(100) not null,
        food_category varchar(100) not null,
        nutrition_summary TEXT not null,
        raw_result_json TEXT,
        primary key (id)
    );

    create table meal_image (
        created_at timestamp(6),
        id bigint generated by default as identity,
        meal_record_id bigint not null,
        updated_at timestamp(6),
        image varchar(255) not null,
        primary key (id)
    );

    create table meal_nutrition (
        carbohydrate_g float(53) not null,
        fat_g float(53) not null,
        kcal integer not null,
        protein_g float(53) not null,
        sodium_mg float(53) not null,
        sugar_g float(53) not null,
        id bigint generated by default as identity,
        meal_record_id bigint not null unique,
        primary key (id)
    );

    create table meal_record (
        health_score integer,
        is_ai_analyzed boolean not null,
        meal_date date not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        recorded_at timestamp(6) not null,
        updated_at timestamp(6),
        name varchar(50) not null,
        meal_category varchar(255) not null check (meal_category in ('MEAL','SNACK','DRINK','ETC')),
        meal_time_slot varchar(255) not null check (meal_time_slot in ('BREAKFAST','LUNCH','DINNER','SNACK','MIDNIGHT_SNACK')),
        memo TEXT,
        scan_type varchar(255) not null check (scan_type in ('CAMERA','IMAGE','DIRECT')),
        primary key (id)
    );

    create table member (
        birthday date,
        onboarding_completed boolean not null,
        suggested_kcal integer,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        social_id bigint,
        updated_at timestamp(6),
        user_id bigint not null unique,
        gender varchar(10) check (gender in ('MALE','FEMALE')),
        meal_style varchar(20) check (meal_style in ('BALANCED','PROTEIN_FOCUSED','CARB_PREFERRED','LATE_NIGHT','INTERMITTENT_FASTING','DESSERT_OBSESSED')),
        name varchar(20),
        nickname varchar(20),
        phone varchar(20),
        social_type varchar(20) check (social_type in ('KAKAO','NAVER')),
        email varchar(50) not null,
        profile_image varchar(255),
        primary key (id)
    );

    create table notification (
        retry_count integer not null,
        created_at timestamp(6),
        failed_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        read_at timestamp(6),
        sent_at timestamp(6),
        updated_at timestamp(6),
        type varchar(30) not null check (type in ('MEAL_REMINDER_OVERDUE','MEAL_REMINDER_NO_TODAY','GROUP_JOIN','MISSION_START','KKINIPOP_REACTION')),
        title varchar(80) not null,
        body varchar(255) not null,
        data_json text,
        failure_reason varchar(255),
        image varchar(255),
        primary key (id)
    );

    create table notification_agree (
        is_agree boolean not null,
        member_id bigint not null,
        type varchar(50) not null check (type in ('KKIROK','GROUP_JOIN_AND_QUIT','KKINIPOP','REACTION')),
        primary key (member_id, type)
    );

    create table notification_agree_history (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table notification_device (
        id bigint generated by default as identity,
        last_used_at timestamp(6),
        member_id bigint not null,
        platform varchar(10) not null check (platform in ('ANDROID','IOS')),
        token varchar(255) not null unique,
        primary key (id)
    );

    create table notification_dispatch_log (
        dispatched_at timestamp(6) not null,
        id bigint generated by default as identity,
        dispatch_key varchar(100) not null unique,
        primary key (id)
    );

    create table onboarding (
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null unique,
        updated_at timestamp(6),
        purpose varchar(30) check (purpose in ('LOSE_WEIGHT','MAINTAIN','GAIN_WEIGHT','HABIT')),
        habits varchar(255),
        primary key (id)
    );

    create table report_suggestions (
        created_at timestamp(6),
        id bigint generated by default as identity,
        report_id bigint not null,
        updated_at timestamp(6),
        title varchar(100) not null,
        content varchar(255) not null,
        primary key (id)
    );

    create table users (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        role varchar(10) not null check (role in ('PENDING','USER','ADMIN')),
        primary key (id)
    );

    create table weekly_report (
        kcal_fri integer,
        kcal_mon integer,
        kcal_sat integer,
        kcal_sun integer,
        kcal_thu integer,
        kcal_tue integer,
        kcal_wed integer,
        total_record_days integer not null,
        week_start_date date not null,
        avg_carbohydrate bigint,
        avg_fat bigint,
        avg_proein bigint,
        avg_sodium bigint,
        avg_sugar bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        main_kcal_title varchar(100),
        intake_comment varchar(255),
        main_kcal_comment varchar(255),
        primary key (id)
    );

    alter table if exists auth_identity 
       add constraint FK7hbhjmd3klwtrx3a37sd8wh0f 
       foreign key (member_id) 
       references member 
       on delete cascade;

    alter table if exists character 
       add constraint FK3f254uixl2761yku71juq626x 
       foreign key (member_id) 
       references member;

    alter table if exists character_exp_history 
       add constraint FKdnp71fwny0k2slrq9uk4p3m1x 
       foreign key (character_id) 
       references character;

    alter table if exists character_status_history 
       add constraint FK7vjsgda0mce6e7nrpltwpk9u7 
       foreign key (character_id) 
       references character;

    alter table if exists item_possession 
       add constraint FK2pk3v3jcep6lrt9mutt7ecq0l 
       foreign key (character_id) 
       references character;

    alter table if exists item_possession 
       add constraint FK9i6pq2d2uhcmmgc634rukp89w 
       foreign key (item_id) 
       references item;

    alter table if exists kkinipop_custom_emoji 
       add constraint FKreexq490sqiepsbni4hchhiqm 
       foreign key (member_id) 
       references member;

    alter table if exists kkinipop_custom_emoji 
       add constraint FKf5757wmo3fqc87kxwhfljta5g 
       foreign key (group_id) 
       references kkinipop_group;

    alter table if exists kkinipop_group_member 
       add constraint FKntq0e7599gjpq51267vor59g3 
       foreign key (group_id) 
       references kkinipop_group;

    alter table if exists kkinipop_group_member 
       add constraint FK9m55merc4q1v743xc38f1xwkw 
       foreign key (member_id) 
       references member;

    alter table if exists kkinipop_mission 
       add constraint FKrobyb9dkjtty2bws7d779atnq 
       foreign key (group_id) 
       references kkinipop_group;

    alter table if exists kkinipop_post 
       add constraint FKsc33e7bf4dykx28jno42tlmxo 
       foreign key (group_id) 
       references kkinipop_group;

    alter table if exists kkinipop_post 
       add constraint FK7yd1r8h5ogewai3qq1ciw89rm 
       foreign key (member_id) 
       references member;

    alter table if exists kkinipop_post 
       add constraint FKj4cqp5rqqk4ipcs5et1y8jhi6 
       foreign key (mission_id) 
       references kkinipop_mission;

    alter table if exists kkinipop_reaction 
       add constraint FKfbn95hnaf0ghw2pba9mltqeik 
       foreign key (member_id) 
       references member;

    alter table if exists kkinipop_reaction 
       add constraint FKhq0ca5d43qep5m4oyd3x19xom 
       foreign key (post_id) 
       references kkinipop_post;

    alter table if exists meal_ai_analysis 
       add constraint FKfscxfkg6cgfeymg5wg4r56amc 
       foreign key (meal_record_id) 
       references meal_record;

    alter table if exists meal_image 
       add constraint FKe601rv9wqk8qabm74q2u6kdk5 
       foreign key (meal_record_id) 
       references meal_record;

    alter table if exists meal_nutrition 
       add constraint FKhniv3qjreho7n6ew6yu859mmm 
       foreign key (meal_record_id) 
       references meal_record;

    alter table if exists meal_record 
       add constraint FK2lvdgvi0obe71y4msnv6ri0nm 
       foreign key (member_id) 
       references member;

    alter table if exists member 
       add constraint FKe6yo8tn29so0kdd1mw4qk8tgh 
       foreign key (user_id) 
       references users 
       on delete cascade;

    alter table if exists notification 
       add constraint FK1xep8o2ge7if6diclyyx53v4q 
       foreign key (member_id) 
       references member 
       on delete cascade;

    alter table if exists notification_agree 
       add constraint FK88vee0dei84f9c9hgv6s04a3r 
       foreign key (member_id) 
       references member;

    alter table if exists notification_device 
       add constraint FKntvwtk3a4qw1cvc36l4lsli07 
       foreign key (member_id) 
       references member 
       on delete cascade;

    alter table if exists onboarding 
       add constraint FKmg5aur189jnhuws6gyv9v9a47 
       foreign key (member_id) 
       references member;

    alter table if exists report_suggestions 
       add constraint FKofo1p44y0dyfu0bfr0cbohmwo 
       foreign key (report_id) 
       references weekly_report;

    alter table if exists weekly_report 
       add constraint FKmon6pab942plh7c3afyu4i0v8 
       foreign key (member_id) 
       references member;
