create table terms_agreement (
    id bigint generated by default as identity,
    member_id bigint not null,
    terms_id bigint not null,
    is_agree boolean not null,
    agreed_at timestamp(6) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    unique (member_id, terms_id)
);

alter table if exists terms_agreement
   add constraint fk_terms_agreement_member
   foreign key (member_id)
   references member;

alter table if exists terms_agreement
   add constraint fk_terms_agreement_terms
   foreign key (terms_id)
   references terms;
