create table terms (
    id bigint generated by default as identity,
    type varchar(50) not null check (type in ('TERMS_OF_SERVICE','PRIVACY_COLLECTION','PRIVACY_THIRD_PARTY','MARKETING')),
    version integer not null,
    r2_key varchar(255) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    unique (type, version)
);
